version: '3.8'
services:
  jsonote:
    build: .
    container_name: jsonote
    environment:
      - JSONOTE_PATH: "/data"
    volumes:
      - ./data:/data/
    ports:
      - "8088:8088"
    restart: unless-stopped
